### PR TITLE
Feature/store data

### PR DESCRIPTION
**Pull request by shahadat3669**
### Project requirements
- On exit from the app save all the data (books, people, and rentals) into JSON files.
- One per type of data we are storing and named accordingly (e.g. rentals.json)
- On startup of our app load all data from files.

### General requirements
- There are [no linter errors](https://github.com/microverseinc/linters-config).
- Used correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
- Documented work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
- Follow list of [best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).

### CODE REVIEW

**Review by franclobo — APPROVED** [review]
Hi @shahadat3669, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is a pair programming project but it doesn't have a commit from your partner.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by franclobo — COMMENTED** [review]
Hi @shahadat3669 and @GutemaG ,

# STATUS: APPROVED 😃

git-merge

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

## Highlights

- Data is preserved 💯
- No linter errors ✔️
- Descriptive PR ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by shahadat3669** [comment]
@franclobo those two commits from my partner. Unfortunately, I don't know why that not showing.
image

**Comment by franclobo** [comment]
> @franclobo those two commits from my partner. Unfortunately, I don't know why that not showing. image

I'm sorry @shahadat3669 I didn't notice the blanks. Your project is complete it's time to merge it.

**Pull request closed without merging**
